const app = getApp()

Page({
   data:{
     arr:[
       {
         id:1,
         title:"多重轨道火车套装1",
         imgUrl:'../../images/1.jpg'
       },
       {
        id:2,
        title:"多重轨道火车套装1",
        imgUrl:'../../images/1.jpg'
      },
      {
        id:3,
        title:"多重轨道火车套装1",
        imgUrl:'../../images/1.jpg'
      },
      {
        id:4,
        title:"多重轨道火车套装1",
        imgUrl:'../../images/1.jpg'
      },
     ],
     list:[
      {
        id:1,
        title:"多重轨道3火8道3456789876543火车车套装1",
        imgUrl:'../../images/11.jpg',
        price:345
      },
      {
        id:2,
        title:"多重轨套23456723456787865432456754323装1",
        imgUrl:'../../images/12.jpg',
        price:34335
      },
      {
        id:3,
        title:"多重轨道7火车套装1",
        imgUrl:'../../images/13.jpg',
        price:345333
      },
      {
        id:4,
        title:"多重轨道2火车套装1",
        imgUrl:'../../images/14.jpg',
        price:34443
      },
     ]
   }
}
)